# Generated by Django 2.2.6 on 2019-10-18 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre',
            new_name='Genero',
        ),
    ]
